#!/data/data/com.termux/files/usr/bin/bash

# update termux binaries
apt update && apt upgrade -y

termux-setup-storage

apt install proot-distro -y

proot-distro install debian
proot-distro rename debian xenos

# clear proot distro cache
proot-distro clear

XFS=$PREFIX/var/lib/proot-distro/installed-rootfs/xenos
XENOS=$XFS/root

echo " " >> .bash_aliases
echo " " >> .bashrc

# remopve current bash files
rm .bash_aliases
rm .bashrc
rm $XENOS/.bashrc
rm $PREFIX/etc/bash.bashrc

# get bash files
curl -LO https://raw.githubusercontent.com/devedaniele/XenOS/main/.xenos/.bash_aliases
curl -sSL https://raw.githubusercontent.com/devedaniele/XenOS/main/.xenos/bash.bashrc >> $PREFIX/etc/bash.bashrc
curl -LO https://raw.githubusercontent.com/devedaniele/XenOS/main/.xenos/.bashrc
curl -sSL https://raw.githubusercontent.com/devedaniele/XenOS/main/xenos/init >> $XENOS/.bashrc

proot-distro login xenos
