#!/bin/bash

apt update && apt upgrade -y

apt install gnupg curl -y

rm -rf /etc/apt/sources.list
echo "deb http://http.kali.org/kali kali-rolling main contrib non-free" > /etc/apt/sources.list

curl -sSL https://archive.kali.org/archive-key.asc | apt-key add
mv /etc/apt/trusted.gpg /etc/apt/trusted.gpg.d

apt-get update -y && apt-get dist-upgrade -y

apt install git gh sudo make cmake build-essential neovim -y

echo " " >> .bash_aliases

rm .bash_aliases
rm .bashrc
rm /etc/bash.bashrc

curl -LO https://raw.githubusercontent.com/devedaniele/XenOS/main/xenos/.bash_aliases
curl -sSL https://raw.githubusercontent.com/devedaniele/XenOS/main/xenos/bash.bashrc >> /etc/bash.bashrc
curl -LO https://raw.githubusercontent.com/devedaniele/XenOS/main/xenos/.bashrc

gh auth login

git clone https://github.com/nvim-lua/kickstart.nvim.git "${XDG_CONFIG_HOME:-$HOME/.config}"/nvim

rm -rf /root/.config/nvim/.git

sleep 1

exit
